[package]
name = "crystal_forge"
version = "1.0.0"
edition = "2021"
description = "A resource management simulation where players craft and trade crystalline resources"
license = "MIT"
keywords = ["game", "simulation", "resource-management"]

[dependencies]
rand = "0.8"
